config/routes.rb
Rails.application.routes.draw do

	root "pages#index"

	get "/about", to: "pages#show", as: :about

	resources :users, only: [:create]

	resources :sessions, only: [:create]
	get "/logout", to: "sessions#destroy", as: :logout

	resources :posts, only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts, dependent: :destroy
	has_secure_password
	validates :email, presence: true, 
					  length: {minimum: 2},
					  uniqueness: true,
					  format: {with: /@/, message: "You can't fool me - that's not a valid email."}
	validates :password, presence: true,
						 length: {minimum: 6}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # checks to see if user is logged in currently
  def logged_in?
    current_user != nil
  end

  # allows us to use `current_user` and 'logged_in?' in views
  helper_method :current_user, :logged_in?
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end

	def show
		@post = Post.new
		@posts = Post.all
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	# add new post to database
	def create
		# redirect user if already logged in
		if current_user
			post = Post.new(post_params)
			post.user_id = current_user.id
			if post.save
				flash[:notice] = "Successfully saved post."
				redirect_to about_path
			else
				flash[:error] = post.errors.full_messages.join(', ')
				redirect_to about_path
			end
		else
			flash[:error] = "Need to login to create post."
			redirect_to root_path
		end
	end

	def destroy
		if post = Post.find(params[:id])
			if current_user
				flash[:notice] = "Successfully deleted post!"
				post.delete
				redirect_to about_path
			else
				flash[:error] = "You need to login in to delete post."
				redirect_to root_path
			end
		else
			flash[:error] = post.errors.full_messages.join(', ')
			redirect_to about_path
		end
	end

	private
		def post_params
			params.require(:post).permit(:text, :user_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(user_params[:email])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Successfully logged in!"
      redirect_to root_path
    else
      flash[:error] = "Incorrect email or password. Please try again."
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out!"
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # add new user to database
  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "Successfully signed up!"
      redirect_to root_path
    else
      flash[:error] = user.errors.full_messages.join(', ')
      redirect_to root_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<title>NightMaze</title>

	<%= render "game" %>

	<!-- Favicon -->
	<link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<!-- Bootstrap Optional CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

	<%= stylesheet_link_tag "application", media: "all" %>

	<%= csrf_meta_tags %>

</head>
<body>

	<%= render "navbar" %>

	<div class="container text-center">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert #{name == 'error' ? 'alert-danger' : 'alert-info'}" %>
		<% end %>
	</div>

	<%= yield %>

	<!-- jQuery -->
	<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Bootstrap JS -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	<%= javascript_include_tag "application" %>

</body>
</html>

app/views/pages/_game.html.erb
	<script type='text/javascript' src='https://ssl-webplayer.unity3d.com/download_webplayer-3.x/3.0/uo/jquery.min.js'></script>
	<script type="text/javascript">
		var unityObjectUrl = "http://webplayer.unity3d.com/download_webplayer-3.x/3.0/uo/UnityObject2.js";
		if (document.location.protocol == 'https:')
			unityObjectUrl = unityObjectUrl.replace("http://", "https://ssl-");
		document.write('<script type="text\/javascript" src="' + unityObjectUrl + '"><\/script>');
	</script>
	<script type="text/javascript">
		var config = {
			width: 960, 
			height: 600,
			params: { enableDebugging:"0" }	
		};
		var u = new UnityObject2(config);

		$(function() {

			var $missingScreen = $("#unityPlayer").find(".missing");
			var $brokenScreen = $("#unityPlayer").find(".broken");
			$missingScreen.hide();
			$brokenScreen.hide();
				
			u.observeProgress(function (progress) {
				switch(progress.pluginStatus) {
					case "broken":
						$brokenScreen.find("a").click(function (e) {
							e.stopPropagation();
							e.preventDefault();
							u.installPlugin();
							return false;
						});
						$brokenScreen.show();
					break;
					case "missing":
						$missingScreen.find("a").click(function (e) {
							e.stopPropagation();
							e.preventDefault();
							u.installPlugin();
							return false;
						});
						$missingScreen.show();
					break;
					case "installed":
						$missingScreen.remove();
					break;
					case "first":
					break;
				}
			});
			u.initPlugin($("#unityPlayer")[0], "<%= asset_path "game.unity3d" %>" );
		});
	</script>

app/views/pages/_loginform.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h3 class="text-center">Login</h3>
		<hr>
		<%= form_for :user, url: sessions_path, :html => { :multipart => true, :id => "login_form" } do |f| %>
		<div class="form-group">
			<label for="email">Email</label>
			<%= f.email_field :email, placeholder: "Email", autofocus: true, class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="password">Password</label>
			<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
 		</div>
 		<hr>
 		<%= f.submit "Login", class: "btn btn-primary btn-block" %>
 		<% end %>
		<br><br>
	</div>
</div>

app/views/pages/_navbar.html.erb
	<header>
		<nav class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand"><%= image_tag("spider.png", :alt => "Logo", :class => "navbar_image") %></a>
				<a class="navbar-brand creepy-text" href="/">NightMaze</a>
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="/about">About</a></li>
			</ul>
			<% if logged_in? %>
				<a class="btn navbar-btn navbar-right btn-danger" href="/logout" id="logout-button">Log out</a>
				<ul class="nav navbar-nav navbar-right">
					<li><a class="navbar-header">Welcome, <%= current_user.username %></a></li>
				</ul>
			<% else %>
				<a class="btn navbar-btn navbar-right btn-default" data-toggle="modal" data-target="#signup-modal" id="signup-button">Sign Up</a>
				<a class="btn navbar-btn navbar-right btn-primary" data-toggle="modal" data-target="#login-modal">Login</a>
				<div class="modal fade" id="signup-modal">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-body">
								<%= render "signupform" %>
							</div>
						</div>
					</div>
				</div>
				<div class="modal fade" id="login-modal">
					<div class="modal-dialog">
						<div class="modal-content">
							<div class="modal-body">
								<%= render "loginform" %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
			</div>
		</nav>
	</header>

app/views/pages/_postform.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h3 class="text-center">New Post</h3>
		<hr>
		<%= form_for @post do |f| %>
		<div class="form-group">
			<%= f.text_area :text, placeholder: "Enter post", autofocus: true, class: "form-control" %>
		</div>
		<hr>
		<%= f.submit class: "btn btn-danger btn-block" %>
		<% end %>
		<br><br>
	</div>
</div>

app/views/pages/_signupform.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h3 class="text-center">Sign Up</h3>
		<hr>
		<%= form_for :user, url: users_path, :html => { :multipart => true, :id => "new_user" } do |f| %>
		<div class="form-group">
			<label for="username">Username</label>
			<%= f.text_field :username, placeholder: "Username", autofocus: true, class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="email">Email</label>
			<%= f.email_field :email, placeholder: "Email", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="password">Password</label>
			<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
		</div>
		<hr>
		<%= f.submit "Sign Up", class: "btn btn-primary btn-block" %>
		<% end %>
		<br><br>
	</div>
</div>

app/views/pages/_userform.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h2>Sign Up</h2>
		<hr>
		<%= form_for :user, url: users_path, :html => { :multipart => true, :id => "new_user" } do |f| %>
		<div class="form-group">
			<label for="username">Username</label>
			<%= f.text_field :username, placeholder: "Username", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="email">Email</label>
			<%= f.email_field :email, placeholder: "Email", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="password">Password</label>
			<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
		</div>
		<hr>
		<%= f.submit "Sign Up", class: "btn btn-primary btn-block" %>
		<% end %>
		<br><br>
	</div>
</div>

app/views/pages/index.html.erb
<h1 class="text-center creepy-text">NightMaze</h1>
<div class="content">
	<div id="unityPlayer">
		<div class="missing">
			<a href="//unity3d.com/webplayer/" title="Unity Web Player. Install now!">
				<%= image_tag("getunity.png", :alt => "Unity Web Player. Install now!", :class => "get_unity") %>
			</a>
		</div>
		<div class="broken">
			<a href="//unity3d.com/webplayer/" title="Unity Web Player. Install now! Restart your browser after install.">
				<%= image_tag("getunityrestart.png", :alt => "Unity Web Player. Install now! Restart your browser after install.", :class => "get_unity") %>
			</a>
		</div>
	</div>
	<h3 class="text-center">For downloadable versions of this game, please click <a href="https://www.dropbox.com/sh/kfw6z3qoqsw2qcr/AABYp8yzrxoD1jC7KqNwxbela?dl=0" target="_blank">here</a>.</h3>
</div>

app/views/pages/show.html.erb
<div class="container">
	<div class="text-center">
		<h1 class="creepy-text">About NightMaze</h1>
		<a href="https://github.com/sswbelser/NightMaze" class="btn btn-round btn-clear btn-github" id="githubIcon" target="_blank"><i class="fa fa-github-square fa-4x"></i></a>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-6 about-div">
			<h3 class="text-center creepy-text">A Storm-Hill Game</h3>
			<p>You have slipped into a deep pit with no visible way out. As you turn on your flashlight you find that you are in some sort of maze. It is dark and you hear noises. You have to run. You have to escape! NightMaze is an exciting first person maze runner with the goal of surviving the monsters of the maze and finding the way out. You are trapped in the maze with just a flashlight and a weapon. Can you make it?<br><br>The Storm-Hill duo met in college and quickly became close friends, bonding over common interest in video games - both vintage and modern. After college, the two kept in contact and joined an intesive course to teach themselves how to code. Throughout the course, they both took it upon themselves to learn new tools, with the ultimate goal of building their own games. While they experimented with other game engines, they eventually discovered <a href="http://unity3d.com/unity/" target="_blank">Unity</a>. With Unity, they found just how fun it could be to build 3D mobile games.<br><br>NightMaze is the first game to come from the Storm-Hill team, and we hope you enjoy it!</p>
			<hr>
			<%= image_tag("storm_hill.jpg", class: "about-image") %>
			<ul class="text-center" id="about-ul">
				<li><a href="http://www.sswbelser.com" target="_blank">Sabastian Belser</a></li>
				<li><a href="http://www.codingforsmiles.com" target="_blank" id="sean">Sean Hill</a></li>
			</ul>
			<br><br>
		</div>
		<div class="col-md-6">
			<!-- Posts -->
			<h3 class="text-center creepy-text">What do you think?</h3>
			<br>
			<div class="text-center">
				<a class="btn btn-danger" data-toggle="modal" data-target="#post-modal" id="post-button">New Post</a>
			</div>
			<div class="modal fade" id="post-modal">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-body">
							<%= render "postform" %>
						</div>
					</div>
				</div>
			</div>
			<br><br>
			<% @posts.each do |post| %>
				<div class="panel panel-danger">
					<div class="panel-heading">
						<h4 class="creepy-text"><%= post.user.username %></h4>
					</div>
					<div class="panel-body">
						<p><%= post.text %></p>
						<% if post.user == current_user %>
							<%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, post_path(post), class: "btn", method: :delete, data: { confirm: 'Are you sure?' } %>
						<% end %>
					</div>
				</div>
				<hr>
			<% end %>
		</div>
	</div>
</div>